-------------------------- MODULE property --------------------------
(***************************************************************************)
(* P08 -- Transport Confidentiality + Authentication.                       *)
(*                                                                         *)
(* Phase-2 deliverable of the zkCoins 100% Logical Verification Initiative: *)
(* the encrypted bundle-delivery layer (spec Sec. 4) proven UNBOUNDED with  *)
(* Apalache via an inductive invariant -- safety holds in EVERY reachable   *)
(* state, for an arbitrary number of publish/replicate/sign/ack/retry/drop  *)
(* transitions, not just to a fixed depth.                                  *)
(*                                                                         *)
(* THE CLAIM (matches Pass-3 audit P8, HIGH with a LOW sub-finding F17):    *)
(*   The off-chain delivery channel is confidential and its ACKs are        *)
(*   unforgeable AND freshness-bound, so a captured ACK can never be         *)
(*   replayed to make the sender drop its only retained copy early. The      *)
(*   composite safety property INV_P8 is the conjunction of:                 *)
(*     (i)   CONFIDENTIALITY -- no party outside the ivk / K_tx holder sets  *)
(*           can ever decrypt a delivery payload or a bundle; the relay /    *)
(*           eavesdropper Eve learns only the opaque outer envelope          *)
(*           (Transport.TrAvailabilityNotSafety over the CanDecrypt          *)
(*           discipline, A8-A11).                                            *)
(*     (ii)  AUTHENTICATION / ACK INTEGRITY -- an ACK is accepted only if it *)
(*           is op-signed by the recipient AND nonce-fresh for the current   *)
(*           attempt; no replayed-ACK acceptance                            *)
(*           (Transport.TrAckFreshness, A7 + F17 fix).                       *)
(*     (iii) SENDER-RETENTION SAFETY -- the sender never releases its only   *)
(*           copy + K_tx before both a valid ACK and k independent replicas  *)
(*           are confirmed (Transport.TrSenderRetainsUntilSafe).            *)
(*                                                                         *)
(* GROUNDED IN THE SPECIFICATION (baseline docs@ed7fdece, spec-v1.1):       *)
(*   - Sec. 4.1 -- the transport (op key, node-as-relay) is trusted only    *)
(*     for availability and metadata minimisation, never for correctness: a  *)
(*     relay can withhold a bundle but can neither forge nor alter one.      *)
(*   - Sec. 4.2 -- the delivery event carries no amount/asset/recipient/     *)
(*     sender (those live only inside the NIP-44 ciphertext); the K_tx-      *)
(*     encrypted bundle and the IVPK-encrypted, NIP-59 gift-wrapped delivery *)
(*     event; the normative ACK + retry rule with the per-attempt ack_nonce  *)
(*     (the F17 fix, docs#36 / docs#40) and the sender-retention rule.       *)
(*   - Sec. 4.6 -- the replication target k (default 3, MUST NOT be < 2) and *)
(*     the normative safety invariant "custody safety MUST NOT depend on     *)
(*     availability" -- losing availability impairs recovery but can never   *)
(*     cause theft.                                                          *)
(*                                                                         *)
(* THE F17 NOTE. Pass-3 flagged F17 (LOW): the audited spec snapshot made    *)
(* the ACK NOT nonce-bound, so a captured ACK was valid forever for a        *)
(* (detect_tag, blob_id) pair and could be replayed to trigger an early      *)
(* drop. F17 was subsequently FIXED in the spec (the ack_nonce binding,      *)
(* docs#36, folded into baseline b6972b8). The Transport module -- and hence *)
(* this property -- models the FIXED form: AckAccepts requires both the op   *)
(* signature (A7) and a.ackNonce = trAttemptNonce. The negative control      *)
(* below reintroduces the pre-fix behaviour and shows the replay returns.    *)
(*                                                                         *)
(* MODELLING ABSTRACTIONS (deliberate, stated openly; inherited from         *)
(* module/Transport.tla and module/Assumptions.tla):                        *)
(*   - NIP-44 v2 encryption and NIP-59 gift-wrap (Sec. 4.2) are NOT modelled *)
(*     byte-for-byte. Their only logical content is "who can read the         *)
(*     plaintext", captured by the A8-A11 oracle CanDecrypt over the per-     *)
(*     object key-holder set. The relay/eavesdropper Eve is absent from every *)
(*     holder set, so it decrypts nothing.                                   *)
(*   - The BIP-340 ACK signature is the A7 EUF-CMA oracle: the recipient's    *)
(*     op enters trAuthorised for the current attempt's ack tag only via the  *)
(*     honest RecipientSigns action, and SigValid tests membership. Nobody    *)
(*     else can produce that pair.                                           *)
(*   - "k independent replicas" is a SET of distinct holder ids; |replicas|  *)
(*     >= k is the replication-confirmed test. The backoff/retry SCHEDULE    *)
(*     (30 s..1 h) is liveness and abstracted to a non-deterministic Retry    *)
(*     that just refreshes the nonce.                                        *)
(*                                                                         *)
(* WHY THE MODEL EARNS ITS KEEP (negative controls, recorded in notes.md):  *)
(*   (a) Drop the nonce-equality conjunct a.ackNonce = trAttemptNonce from   *)
(*       AckAccepts -> a stale captured ACK is accepted -> TrAckFreshness     *)
(*       fails (the pre-F17-fix replay returns).                             *)
(*   (b) Drop the trAckOk guard from Drop -> the sender releases its only     *)
(*       copy with no ACK -> TrSenderRetainsUntilSafe fails.                  *)
(***************************************************************************)
EXTENDS Transport

(***************************************************************************)
(* THE COMPOSITE SAFETY PROPERTY. The three normative transport guarantees  *)
(* of Sec. 4.1 / 4.2 / 4.6, conjoined. Each conjunct is a named invariant   *)
(* of module/Transport.tla; INV_P8 is the property this certificate proves.  *)
(***************************************************************************)
\* @type: () => Bool;
INV_P8 ==
  /\ TrAvailabilityNotSafety     \* (i)   confidentiality   (Sec. 4.1/4.6, A8-A11)
  /\ TrAckFreshness              \* (ii)  ACK integrity+freshness (Sec. 4.2, A7, F17 fix)
  /\ TrSenderRetainsUntilSafe    \* (iii) sender-retention safety (Sec. 4.2/4.6)

(***************************************************************************)
(* INDUCTIVE INVARIANT. INV_P8 is conjoined with TrTypeOK -- the finite      *)
(* structural facts a checker can enumerate (phase domain, replica set       *)
(* subset of Holders, the A7 oracle only ever holding the recipient's op     *)
(* key). TrTypeOK is the state-bounding fact that lets the SMT step quantify  *)
(* over well-formed states; INV_P8's three conjuncts are then each preserved *)
(* by every action under the phase guards (see notes.md for the per-action   *)
(* argument). No further strengthening is required: the dropped-once-and-     *)
(* frozen discipline (every action is guarded by trPhase = "published") plus *)
(* TrTypeOK closes the induction.                                            *)
(***************************************************************************)
\* @type: () => Bool;
IndInv ==
  /\ TrTypeOK
  /\ INV_P8

(***************************************************************************)
(* Assignment-form restatement of IndInv, used as the --init predicate of   *)
(* the inductive-step check. Apalache requires every variable to be ASSIGNED *)
(* in an init predicate; a bare membership/implication is not an assignment  *)
(* form. Each variable is bound by an `\in` over its (finite) type domain,   *)
(* then the IndInv body is asserted as a state constraint. This is           *)
(* logically equivalent to IndInv: the `\in` bounds are exactly TrTypeOK's   *)
(* structural facts, and the asserted IndInv pins the rest.                  *)
(*                                                                         *)
(* trDelivery is assigned by reconstructing the record from its component    *)
(* domains (the only delivery event the machine ever publishes has the fixed *)
(* opaque handles DetectTag/Epk/BlobId and locators = Holders; its ackNonce  *)
(* tracks an attempt nonce). trAuthorised ranges over the recipient-op pairs *)
(* the oracle can hold (A7: pair[1] = RecipientOpPk).                        *)
(*                                                                         *)
(* FINITE NONCE UNIVERSE (NonceU) -- the uniformity argument. The attempt     *)
(* nonce and the authorised ack tags are coupled only by EQUALITY            *)
(* (TrAckFreshness asks one specific pair membership; AckAccepts checks one   *)
(* equality), so the inductive step is uniform in the nonce universe: a       *)
(* finite universe with at least the attempt nonce, an earlier (stale) nonce, *)
(* and a fresh-retry successor certifies the general result. NonceU is a      *)
(* free finite set of nonce values for the START state; the POST-state        *)
(* invariant IndInv places NO bound on the nonce, so a Retry stepping to a    *)
(* successor outside NonceU is still checked (notes.md records a larger-       *)
(* NonceU confirmation). Apalache cannot map over the infinite carrier Int,   *)
(* so a finite NonceU is also what keeps the step a decidable SMT query.      *)
(***************************************************************************)
\* @type: () => Set(Int);
NonceU == 0 .. 3

\* @type: () => Bool;
IndInvInit ==
  /\ trPhase \in { "published", "dropped" }
  /\ \E n \in NonceU :
       trDelivery = MkDeliveryEvent(DetectTag, Epk, BlobId, BlobLocators, n)
  /\ trAttemptNonce \in NonceU
  /\ trAckOk \in BOOLEAN
  /\ trReplicas \in SUBSET Holders
  /\ trSenderHasCopy \in BOOLEAN
  /\ trAuthorised \in SUBSET ({ RecipientOpPk } \X { AckMsgTag(m) : m \in NonceU })
  /\ IndInv

(***************************************************************************)
(* Constant initialiser (Apalache --cinit). Reuses the smoke instance fixed  *)
(* in module/Transport.tla: one sender node + two other independent holders  *)
(* (so k = 3 is reachable), recipient op pubkey distinct from Eve, ivk/K_tx  *)
(* holders = recipient devices, Eve in neither holder set. The inductive     *)
(* argument is uniform in the instance sizes -- every conjunct is a local    *)
(* structural fact and every action preserves it independently of |Holders|  *)
(* (notes.md records a confirming run at a larger instance).                 *)
(***************************************************************************)
\* @type: () => Bool;
ConstInit == TrConstInit

=============================================================================
